CLASSIFIER: 
  name: resnet50
  mode: supcon
  head: mlp
  feat_dim: 128
COMMON:
  workers: 4
  batch_size: 128
  epochs: 300
  temp: 0.1
  data_path: data/cifar-10-python.tar.gz
  logdir: logs
  save_freq: 20
  verbose: 1
  seed: 2021
  continue_from: logs/resnet50-supcon-final/final
OPTIMIZER:
  name: momentum
  params:
    momentum: 0.9
    weight_decay: 0.0001
SCHEDULER:
  name: cosine
  warm_up_step: 2000
  params:
    learning_rate: 0.03
    T_max: 300